name: wf-ci-develop
on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
jobs:
  build-develop-job:
    runs-on: ubuntu-latest
    steps:
      - name: Chekcout Repo 
        uses: actions/checkout@v4
      - name: Logint Docker Hub To authorize Github Actions to integrate with Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: Create Docker Image Locally on the Runner
        run: docker build -t zsaing/kpkadvantures:1.0 .
      - name: Check Image Created Correctly
        run: docker images
      - name: Run Docker Container Locally from the created Image
        run: docker run -p 3333:80 -d --name container_runner  zsaing/kpkadvantures:1.0
      - name: Check Running Containers
        run: docker ps 
      - name: Now Push Docker Image onto the Dockerhub
        run: docker push zsaing/kpkadvantures:1.0
      - name: Do the Termination House Keeping At Runner
        run: |
          docker stop container_runner 
          docker rm container_runner
          docker rmi zsaing/kpkadvantures:1.0
          echo "Image And Container Deleted Successfuly"